export const schoolsData = [
  {
    id: "New-East-University",
    name: "New East University",
    description:
      "Established in 1988, the Near East University is situated in the capital city of North Cyprus, Nicosia, and has gained a reputation as a leading international higher education institution. It offers an extensive range of undergraduate and postgraduate programs, attracting over 26,000 students from more than 100 countries. With 20 faculties comprising 220 departments and programs, 8 graduate schools offering around 218 graduate and postgraduate programs, and 3 high schools, the university provides diverse educational opportunities. The Near East University holds significant international memberships, including the European University Association (EUA), the International Association of Universities (IAU) affiliated with UNESCO, the International Society for Engineering Education (IGIP), and the Joint Commission International (JCI). It also collaborates with 118 other national and international institutions and foundations, and is actively pursuing additional memberships across various disciplines. The university has achieved numerous milestones within Cyprus. Notably, it is home to the only Faculty of Medicine in North Cyprus, as well as the first and only Faculty of Dentistry. The Dentistry Clinics at the university have obtained JCI accreditation, making them the world's first accredited private dentistry clinics. Moreover, the university houses a state-of-the-art Super Computer, renowned for its advanced capabilities and its support of international research projects, including the renowned CERN project. The university's Grand Library is the largest and most comprehensive in the Eastern Mediterranean region, boasting an extensive collection of over a million printed materials and 115 million electronic sources. The library serves as a venue for numerous national and international conferences. In addition, the Near East University Hospital stands as a leading research and training hospital in the Eastern Mediterranean region. Another notable accomplishment is the establishment of the first and only Faculty of Pharmacy in North Cyprus. The university offers a wide array of on-campus facilities and services to its students, ensuring a holistic experience. These include sports fields, shops, restaurants, dormitories accommodating up to 5000 people, health and fitness centers, cafes, student clubs, a radio-TV center, and an Olympic swimming pool. Furthermore, students have access to national and international banks, travel agencies, a post office, and scheduled coaches that operate between the city and the airport throughout the day. The campus is equipped with 24-hour security and health services to ensure the well-being of its students. Since its establishment, the Near East University has been committed to cultivating self-assured, highly qualified, dedicated, and determined individuals. Through its remarkable progress and development, it has become the largest higher education institution and cultural center in Cyprus.",
    url: "neu.png",
  },

  {
    id: "Cyprus-International-University",
    name: "Cyprus International University",
    description:
      "Cyprus International University is located in North Cyprus, just outside the capital city of Nicosia. Founded in 1997, the University offers over 100 degree programs to students from over 100 countries. The university is affiliated with the Levent Group of companies and has close links with companion enterprises in construction, international trade, manufacturing, energy, banking, dairy farming, poultry farming, agriculture, and various other sectors. This enables the university to offer an outstanding hands-on learning experience spanning the classroom, campus, and a wide variety of work environments. Cyprus International University is governed by the Rectorate. The Rectorate not only leads but also represents the university externally and coordinates the cooperation of university members internally. The Rectorate consists of the Rector, Vice-Rectors, and General Secretary. The Rector is the Chair of the Rectorate and the spokesperson for both the Rectorate and the University. Cyprus International University are committed to advancing in academic excellence, encourage sustainable development, engage in continuous innovation, and to create a diverse community by empowering students to continue to achieve and pursue lifelong success. Since its establishment, Cyprus International University (CIU) has placed great importance to global development and cooperation due to which it has become an internationally recognized and respected institution of higher education CIU continues to develop a global presence by entering several existing and on-going agreements. CIU has received accreditation for its programs from numerous reputable accreditation institutions and has become a member of many organizations to improve the quality of education it offers. Starting with 81 students and 45 staff in 1997, CIU has grown exponentially reaching 20,000 students and more than 1000 staff in only 26 years.The strategic geopolitical location of the island of Cyprus and its proximity to the birthplace of civilization has played an important role in what Cyprus is today; a small but very international island. This international identity became the inspiration for our name. Cyprus International University has its roots in the vision of Mr. Özer Boyacı who set out to establish an institution that would make a mark on higher education in North Cyprus. After 26 years, the fulfillment of his vision can be seen in the countless success stories that came out of CIU, an educational infrastructure second to none on the island, a campus encompassing over a million square meters, an increasing focus on research, social responsibility, environment and culture and an ever growing number of graduates in over a hundred different countries.",
    url: "ciu.png",
  },
  {
    id: "SSBM",
    name: "SSBM",
    description:
      "SSBM is a global, innovative and unique school with students from all around the world. Our programs were designed with over 30 industry partners. We guarantee Swiss Quality Education and excellence. SSBM Geneva is principally located in Geneva, Switzerland and is registered in the canton of Geneva under the registration number CHE-131.073.981. SSBM VISION is to be a unique, innovative and international business & management school offering premium research, practice and education. They are committed to continuously provide educational excellence and our expertise in business education through our innovative cutting-edge technology and our high-quality learning experience supported by relevant research. They encourage diversity and global connectivity between their students, faculty and business partners, while placing high importance on the benefits that their business can bring to the society as well as the environment. SSBM Geneva will help you acquire habits of reflection and critical thinking that are crucial to understand today’s society. Recognizing the facts that individual success is intertwined with the larger world, we encourage students to engage in improving their critical thinking. Swiss School of Business and Management Geneva sits right at the heart of business in the vibrant city of Geneva, Switzerland. Situated along the banks of Lake Geneva at the foot of the Alps, Geneva sparkles as one of Europe’s most beautiful cities. Geneva is a global city, a financial center, and a worldwide center for diplomacy due to the presence of numerous international organizations, including the headquarters of many companies and international agencies. SSBM Geneva faculty and collaborators have provided consulting, teaching and project-based service to over 70 international and national companies. They believe that academic knowledge has to be in tight connection with the industry, which is the driving force for better knowledge in today’s rapidly changing environment.",
    url: "ssbm.png",
  },
];
